### ISSUE TITLE
Fork this project to a new GH org, and deprecate it

### ISSUE THREAD

**Issue by tomers** [computerlyrik/dymoprint#114]
As discussed in PR #113, we plan to fork this project in a new Github organization. This issue is for discussing and managing related logistics.

### Name
Reasonable names are hard to find, as they are mostly already taken by other companies and products.
I consulted OpenAI, and came up with the name 'LabelGenious'. @maresb, @tomek-szczesny please approve.

**Comment by tomek-szczesny** [comment]
What's wrong with keeping the old name? 
I don't think we have to pretend it's not a direct continuation of this project.

EDIT: On the other hand, other projects did change name for similar reasons. Such as yt-dlp.
How about dymoprint+?

**Comment by maresb** [comment]
We'd like this project to be able to expand to non-Dymo printers.

I think `LabelGenious` is misspelled and should be `LabelGenius`. That aside I personally have fairly negative connotations around the word "genius".

Not sure if it's much better, but maybe simplelabel or labelsimple?

**Comment by maresb** [comment]
Also, we the name may come out better if we don't include the words "label" or "print". For example we could choose the name of some random obscure animal.

I'd also like to get feedback here from @computerlyrik, @MooVx, @putzio, @aleksas, @systeemkabouter, @claui.

**Comment by tomek-szczesny** [comment]
To pick a name, we could do it the old Unix way. 
Let's settle on a descriptive acronym, such as: Free Label Printer Software.

Then: 
`cat /usr/share/dict/* | grep ^f.*l.*p.*s | awk '{ print length, $0 }' | sort -n | cut -d" " -f2- | uniq`

There you go, **Flopsy**. :)

> From Wikipedia, the free encyclopedia
> 
> Flopsy is a common name for pet [rabbits](https://en.wikipedia.org/wiki/Rabbit).

As close as it gets to a random animal. ;)

**Comment by maresb** [comment]
I really love both the name and the method @tomek-szczesny! I'm so disappointed that it's already [taken](https://pypi.org/project/flopsy/) by [this project](https://github.com/bgribble/flopsy).

**Comment by tomek-szczesny** [comment]
The method was in use as early as in Samba (SMB) days. :)
Norally I'd argue it's not a trademark, but I agree the new name should be at least available in pip.

Any other acronyms we could try?

**Comment by maresb** [comment]
`^la.*pr` gives lamprey. It's available, but lampreys are pretty ugly.

Open source label printer → oversleep. I'm not so convinced.

Maybe something like libreprint?

**Comment by tomers** [comment]
libreprint sounds good.
I checked and it was not taken, besides some obsolete GH project,
*nrc/libreprint
<https://github.com/nrc/libreprint>*, which is 10 y.o.
The name corresponds with other open source projects, such as libreoffice.

**Comment by tomek-szczesny** [comment]
I don't like libreprint, because it implies a much broader spectrum of uses than just label printing. Looks like a name for re-implementation of CUPS. 

Revisiting my best idea so far, _flopsie_ appears to be available.
I tried `^[lfo].*l.*p.*[s]` for Libre/Free/Open Label Printer Software/Suite and can't see any better candidates at the moment.

I don't intend to take part in making the final decision, it's just my contribution to the topic. :)

**Comment by systeemkabouter** [comment]
Hi, 

Just my 2c, Libre Label covers the  purpose and has the nice alliterating quality to it. Libre Tag also seems a good option 


Met vriendelijke groet,

Eelco Maljaars

Infrastructuur ontwikkelaar / security specialist

T +31 (0)6 34 44 53 62
E ***@***.***
I www.lutra-it.eu

**Comment by maresb** [comment]
Thanks for keeping the ideas flowing!

I agree that LibreLabel is better than LibrePrint.

My main concern with "flopsie" is confusion with "flopsy". It'll be really easy for someone to mistype or misremember and end up with the wrong package.

**Comment by tomers** [comment]
I also agree that LibreLabel is better than LibrePrint.
Ben, can we conclude this, and commit to this name?

**Comment by maresb** [comment]
I'd be fine with LibreLabel, but I think we might as well keep the discussion open until tomorrow. People who don't check GitHub over the weekend may have something to contribute. Besides, we're not yet ready to cut a release since `master` and `tomer_fixes` are broken. (See https://github.com/tomers/dymoprint/pull/6 for a potential fix.)

**Comment by maresb** [comment]
Thanks @aleksas for two suggestions via email!

> TagTailor, Taggle

I like Taggle and it's available on PyPI, but unfortunately it seems to be already in use a lot of companies. For example, when I search from France it comes up as the name of a French board game. I'd prefer to aim for something distinctive.

TagTailor seems a reasonable competitor to LibreLabel. (My personal feeling is that LibreLabel is more descriptive.)

**Comment by claui** [comment]
Another suggestion, albeit not entirely distinctive, would be **Labelle.**

It’s a portmanteau of the words *label* and *belle*. Also a pseudo-homonym of the French *la belle.*
Besides, it’s closely related to the German name for a (not-so-obscure) animal, the [Libelle](https://de.wikipedia.org/wiki/Libellen) (dragonfly).

**Comment by tomers** [comment]
Labelle sounds great to me! It is also available in both pip and Github.
It is also a funk rock band: https://en.wikipedia.org/wiki/Labelle

**Comment by tomek-szczesny** [comment]
We got some great suggestions already. I wish I had this kind of support when I named my projects. :)

How do we choose one now? 
I think we can safely rule out LibrePrint, Flopsy/Flopsie, and Taggle.

If I'm not mistaken, we accumulated so far: LibreLabel, LibreTag, TagTailor, Labelle.
I like Labelle the most, because it's just two syllables.

**Comment by maresb** [comment]
Brilliant suggestion @claui! I also like Labelle the most of all the suggestions so far.

Unfortunately when I check it seems that the GitHub organization is already taken: https://github.com/labelle That's an annoyance, but I think we can work around it. For example, we could make an organization called labelle-devs.

**Comment by tomek-szczesny** [comment]
Just checked there are no packages in Arch, Manjaro or AUR named labelle.

> For example, we could make an organization called labelle-devs.

Won't that be confusing though?

**Comment by maresb** [comment]
> Won't that be confusing though?

I don't think so. I'm more concerned about users `pip install`-ing the wrong package. I'm fairly confident that GitHub contributors will be able to locate our repository, e.g. via Google rather than through the organization name. Most projects don't have an organization that matches the project title. Besides, we can have PyPI link back to the correct repository.

These might need just a tiny bit of work /s, but here's some inspiration for a possible logo  :joy:
<img src='https://github.com/computerlyrik/dymoprint/assets/15216687/4ded3b2d-3a12-4816-b9bd-9fa37cf63fee' width=400>
<img src='https://github.com/computerlyrik/dymoprint/assets/15216687/f21c7806-3b6d-4ad4-b451-3cfef7569090' width=400>

**Comment by claui** [comment]
We could ask the owner whether they might be willing to donate the org name to us, given that theirs appears abandoned.

**Comment by claui** [comment]
@jdickan Excuse the intrusion, but are you still using your GitHub organization github.com/labelle? If not, would you consider donating it to this project?

**Comment by tomek-szczesny** [comment]
I think he has to be contacted via linkedin, that github account also appears abandoned.

**Comment by claui** [comment]
> Won't that be confusing though?

I don’t think it’s that confusing. I figure people mostly click on search results or other existing links rather than synthesize a URL by hand.

**Comment by tomers** [comment]
So it seems we all agree on the name `labelle` for the project.
Since https://github.com/labelle is taken, then what would you suggest the
organization name will be? Maybe https://github.com/labelle-org ?

**Comment by tomek-szczesny** [comment]
labelle-org is fine, so would be labelle-devs, labelle-hq..

**Comment by maresb** [comment]
Labelle v1.0.0 has been released on PyPI and is equivalent to Dymoprint v2.4.0.

https://github.com/labelle-org/labelle

![image](https://github.com/computerlyrik/dymoprint/assets/15216687/05b893ba-b7d4-47b6-95c3-2a2ed869c839)

Labelle v1.1.0 will be released soon, and it will be equivalent to the current `master`.

**Comment by tomers** [comment]
Great achievement, Ben!

Thanks a lot for your efforts.
Once we're done with the migration, and after we'll merge my current work
(I'll send a review soon enough), I think we should start publishing this
"new" project in various channels. We should strive to increase our user
base, and encourage developers to assist us.

Regards,
Tomer

**Comment by maresb** [comment]
We did it, [Labelle v1.1.0](https://github.com/labelle-org/labelle/releases/tag/v1.1.0) is out!!! Many thanks to @tomers for rewriting a huge portion of the code!

Please give it a try and make sure I didn't mess anything up with the migration. Once we confirm that it's working well, we'll finish by deprecating Dymoprint.

**Comment by maresb** [comment]
For those determining which version of Dymoprint or Labelle to choose:

* Dymoprint v2.4.0 is the last normal Dymoprint release.
* Dymoprint v2.5.0 is equivalent to v2.4.0, but includes a deprecation message.
* Labelle v1.0.0 is equivalent to Dymoprint v2.4.0
* The Labelle v1 series is designed so that the CLI is backwards-compatible with Dymoprint. (Some CLI options have changed slightly, but their replacements are clearly indicated with deprecation errors.)
* Labelle v2 will contain more substantial updates and will not attempt backwards-compatibility.

The CLI entrypoints have been updated as:

* `dymoprint` → `labelle`
* `dymoprint_gui` → `labelle-gui`

If you have installed Dymoprint with `pipx`, you can uninstall it with

```bash
pipx uninstall dymoprint
```

To install a particular version of Dymoprint or Labelle,

```bash
pipx install "labelle<2"  # Install the latest v1.x version of Labelle
# NOTE: The quotes are required because otherwise `<` is interpreted as a redirect.
```
